name: Project Euler in C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: System Setup
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -qq build-essential cppcheck cpplint
    - uses: actions/checkout@v3
    
    - name: Build
      run: make
    
    - name: Check
      run: make lint
    
    - name: Clean
      run: make clean
